// Generated by gencpp from file ros_start3/SetVelocity.msg
// DO NOT EDIT!


#ifndef ROS_START3_MESSAGE_SETVELOCITY_H
#define ROS_START3_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <ros_start3/SetVelocityRequest.h>
#include <ros_start3/SetVelocityResponse.h>


namespace ros_start3
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace ros_start3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_start3::SetVelocity > {
  static const char* value()
  {
    return "f6aaad2e58fe90e46753c2e927c41798";
  }

  static const char* value(const ::ros_start3::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::ros_start3::SetVelocity > {
  static const char* value()
  {
    return "ros_start3/SetVelocity";
  }

  static const char* value(const ::ros_start3::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::ros_start3::SetVelocityRequest> should match 
// service_traits::MD5Sum< ::ros_start3::SetVelocity > 
template<>
struct MD5Sum< ::ros_start3::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_start3::SetVelocity >::value();
  }
  static const char* value(const ::ros_start3::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_start3::SetVelocityRequest> should match 
// service_traits::DataType< ::ros_start3::SetVelocity > 
template<>
struct DataType< ::ros_start3::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::ros_start3::SetVelocity >::value();
  }
  static const char* value(const ::ros_start3::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_start3::SetVelocityResponse> should match 
// service_traits::MD5Sum< ::ros_start3::SetVelocity > 
template<>
struct MD5Sum< ::ros_start3::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_start3::SetVelocity >::value();
  }
  static const char* value(const ::ros_start3::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_start3::SetVelocityResponse> should match 
// service_traits::DataType< ::ros_start3::SetVelocity > 
template<>
struct DataType< ::ros_start3::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::ros_start3::SetVelocity >::value();
  }
  static const char* value(const ::ros_start3::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_START3_MESSAGE_SETVELOCITY_H
