(cl:defpackage ros_start3-msg
  (:use )
  (:export
   "<GOUNTILBUMPERACTIONGOAL>"
   "GOUNTILBUMPERACTIONGOAL"
   "<GOUNTILBUMPERACTIONFEEDBACK>"
   "GOUNTILBUMPERACTIONFEEDBACK"
   "<GOUNTILBUMPERGOAL>"
   "GOUNTILBUMPERGOAL"
   "<GOUNTILBUMPERACTIONRESULT>"
   "GOUNTILBUMPERACTIONRESULT"
   "<GOUNTILBUMPERACTION>"
   "GOUNTILBUMPERACTION"
   "<GOUNTILBUMPERRESULT>"
   "GOUNTILBUMPERRESULT"
   "<GOUNTILBUMPERFEEDBACK>"
   "GOUNTILBUMPERFEEDBACK"
  ))

