; Auto-generated. Do not edit!


(cl:in-package ros_start3-msg)


;//! \htmlinclude GoUntilBumperGoal.msg.html

(cl:defclass <GoUntilBumperGoal> (roslisp-msg-protocol:ros-message)
  ((target_vel
    :reader target_vel
    :initarg :target_vel
    :type geometry_msgs-msg:Twist
    :initform (cl:make-instance 'geometry_msgs-msg:Twist))
   (timeout_sec
    :reader timeout_sec
    :initarg :timeout_sec
    :type cl:integer
    :initform 0))
)

(cl:defclass GoUntilBumperGoal (<GoUntilBumperGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoUntilBumperGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoUntilBumperGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_start3-msg:<GoUntilBumperGoal> is deprecated: use ros_start3-msg:GoUntilBumperGoal instead.")))

(cl:ensure-generic-function 'target_vel-val :lambda-list '(m))
(cl:defmethod target_vel-val ((m <GoUntilBumperGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_start3-msg:target_vel-val is deprecated.  Use ros_start3-msg:target_vel instead.")
  (target_vel m))

(cl:ensure-generic-function 'timeout_sec-val :lambda-list '(m))
(cl:defmethod timeout_sec-val ((m <GoUntilBumperGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_start3-msg:timeout_sec-val is deprecated.  Use ros_start3-msg:timeout_sec instead.")
  (timeout_sec m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoUntilBumperGoal>) ostream)
  "Serializes a message object of type '<GoUntilBumperGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_vel) ostream)
  (cl:let* ((signed (cl:slot-value msg 'timeout_sec)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoUntilBumperGoal>) istream)
  "Deserializes a message object of type '<GoUntilBumperGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_vel) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timeout_sec) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoUntilBumperGoal>)))
  "Returns string type for a message object of type '<GoUntilBumperGoal>"
  "ros_start3/GoUntilBumperGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoUntilBumperGoal)))
  "Returns string type for a message object of type 'GoUntilBumperGoal"
  "ros_start3/GoUntilBumperGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoUntilBumperGoal>)))
  "Returns md5sum for a message object of type '<GoUntilBumperGoal>"
  "c9b5f8f2aced60d6e82fa76ca79b621a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoUntilBumperGoal)))
  "Returns md5sum for a message object of type 'GoUntilBumperGoal"
  "c9b5f8f2aced60d6e82fa76ca79b621a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoUntilBumperGoal>)))
  "Returns full string definition for message of type '<GoUntilBumperGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Twist target_vel~%int32 timeout_sec~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoUntilBumperGoal)))
  "Returns full string definition for message of type 'GoUntilBumperGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Twist target_vel~%int32 timeout_sec~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoUntilBumperGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_vel))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoUntilBumperGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GoUntilBumperGoal
    (cl:cons ':target_vel (target_vel msg))
    (cl:cons ':timeout_sec (timeout_sec msg))
))
