; Auto-generated. Do not edit!


(cl:in-package ros_start3-msg)


;//! \htmlinclude GoUntilBumperFeedback.msg.html

(cl:defclass <GoUntilBumperFeedback> (roslisp-msg-protocol:ros-message)
  ((current_vel
    :reader current_vel
    :initarg :current_vel
    :type geometry_msgs-msg:Twist
    :initform (cl:make-instance 'geometry_msgs-msg:Twist)))
)

(cl:defclass GoUntilBumperFeedback (<GoUntilBumperFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoUntilBumperFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoUntilBumperFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_start3-msg:<GoUntilBumperFeedback> is deprecated: use ros_start3-msg:GoUntilBumperFeedback instead.")))

(cl:ensure-generic-function 'current_vel-val :lambda-list '(m))
(cl:defmethod current_vel-val ((m <GoUntilBumperFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_start3-msg:current_vel-val is deprecated.  Use ros_start3-msg:current_vel instead.")
  (current_vel m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoUntilBumperFeedback>) ostream)
  "Serializes a message object of type '<GoUntilBumperFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_vel) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoUntilBumperFeedback>) istream)
  "Deserializes a message object of type '<GoUntilBumperFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_vel) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoUntilBumperFeedback>)))
  "Returns string type for a message object of type '<GoUntilBumperFeedback>"
  "ros_start3/GoUntilBumperFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoUntilBumperFeedback)))
  "Returns string type for a message object of type 'GoUntilBumperFeedback"
  "ros_start3/GoUntilBumperFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoUntilBumperFeedback>)))
  "Returns md5sum for a message object of type '<GoUntilBumperFeedback>"
  "3186359c02aecabea670ec7a240a2497")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoUntilBumperFeedback)))
  "Returns md5sum for a message object of type 'GoUntilBumperFeedback"
  "3186359c02aecabea670ec7a240a2497")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoUntilBumperFeedback>)))
  "Returns full string definition for message of type '<GoUntilBumperFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Twist current_vel~%~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoUntilBumperFeedback)))
  "Returns full string definition for message of type 'GoUntilBumperFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Twist current_vel~%~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoUntilBumperFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_vel))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoUntilBumperFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoUntilBumperFeedback
    (cl:cons ':current_vel (current_vel msg))
))
