#export PATH="/opt/local/bin:/usr/local/bin:$PATH"
export ZSH=$HOME/.oh-my-zsh
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jsupratman13/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#oh my zsh customization
plugins=(git extract debian copydir copyfile)

ZSH_THEME="agnoster"
eval `dircolors ~/.solarized/dircolors.ansi-light`
#ZSH_THEME="jreese"

source $ZSH/oh-my-zsh.sh

##ROS
source /opt/ros/indigo/setup.zsh
source ~/catkin_ws/devel/setup.zsh
export ROS_MASTER_URI=http://localhost:11311
export ROS_HOSTNAME=localhost

